#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/testtest1?characterEncoding=utf8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123qwe
#    type: com.alibaba.druid.pool.DruidDataSource